apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-cart-service
  template:
    metadata:
      labels:
        app: shopping-cart-service
    spec:
      containers:
        - name: shopping-cart-service
          image: santiagosanchez03/shopping-cart-service:0.0.2
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-service
spec:
  type: NodePort  # Cambiado a NodePort para hacer accesible el servicio externamente
  selector:
    app: shopping-cart-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30007  # Elige un puerto entre 30000-32767

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: tarampampam/error-pages
          env:
            - name: ERROR_CODE
              value: "500"

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: error-pages
spec:
  replicas: 1
  selector:
    matchLabels:
      app: error-pages
  template:
    metadata:
      labels:
        app: error-pages
    spec:
      containers:
        - name: error-pages
          image: tarampampam/error-pages
          env:
            - name: TEMPLATE_NAME
              value: "lost-in-space"
            - name: SHOW_DETAILS
              value: "true"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: error-pages
spec:
  type: NodePort  # Cambiar a NodePort para exponer el servicio
  selector:
    app: error-pages
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30009  # Elige un puerto entre 30000-32767
